export const Users = [
  {
    id: 1,
    profilePicture: "assets/p1.jpeg",
    userName: "Aditi Singh",
  },
  {
    id: 2,
    profilePicture: "assets/p2.webp",
    userName: "Faiza Sins",
  },
  {
    id: 3,
    profilePicture: "assets/p3.jpeg",
    userName: "Anjali Verma",
  },
  {
    id: 4,
    profilePicture: "assets/p4.webp",
    userName: "Rohit Roy",
  },
  {
    id: 5,
    profilePicture: "assets/p5.jpeg",
    userName: "Nitin Gupta",
  },
  {
    id: 6,
    profilePicture: "assets/p6.webp",
    userName: "Anu Malik",
  },
  {
    id: 7,
    profilePicture: "assets/p7.webp",
    userName: "Kiara Ben",
  },
  {
    id: 8,
    profilePicture: "assets/p8.jpeg",
    userName: "Saras Kumari",
  },
  {
    id: 9,
    profilePicture: "assets/p9.jpg",
    userName: "Akriti Advani",
  },
  {
    id: 10,
    profilePicture: "assets/p10.jpg",
    userName: "Nancy Mathew",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hated For None",
    photo: "assets/post1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Ancient",
    photo: "assets/post2.jpeg",
    date: "1 hour ago",
    userId: 2,
    like: 10,
    comment: 2,
  },
  {
    id: 3,
    
    photo: "assets/post3.jpeg",
    date: "5 Year ago",
    userId: 3,
    like: 20,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post4.webp",
    date: "3 Months ago",
    userId: 4,
    like: 22,
    comment: 7,
  },
  {
    id: 5,
    photo: "assets/post5.webp",
    date: "6 Hours ago",
    userId: 5,
    like: 40,
    comment: 1,
  },
  {
    id: 6,
    photo: "assets/post6.jpeg",
    date: "9 Months ago",
    userId: 6,
    like: 11,
    comment: 6,
  },
  {
    id: 7,
    desc: "Your Patience is your Power",
    photo: "assets/post7.jpeg",
    date: "2 Months ago",
    userId: 7,
    like: 11,
    comment: 7,
  },
  {
    id: 8,

    photo: "assets/post8.webp",
    date: "7 Months ago",
    userId: 8,
    like: 11,
    comment: 8,
  },
  {
    id: 9,
    photo: "assets/post9.jpeg",
    date: "9 Min ago",
    userId: 9,
    like: 11,
    comment: 9,
  },
  {
    id: 10,
    desc: "Yummm...",
    photo: "assets/post10.jpeg",
    date: "2 Min ago",
    userId: 10,
    like: 11,
    comment: 10,
  },
];
